name: CI

on: push

jobs:
  test:
    uses: jill64/.github/.github/workflows/run-vitest.yml@main
    with:
      pre-test: npm run package
  test-e2e:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@da9c86b314ddbcf55eda49b3580740108d251bd9 # v3.0.0
    with:
      hosting-provider: cloudflare
